image: registry.windmaker.net:5005/a-castellano/limani/base_golang_1_15:202104052102

stages:
    - unit_tests
    - integration_tests
    - coverage
    - report
    - scan
    - deploy

unit_tests:
  stage: unit_tests
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-config-reader
    - cd $GOPATH/src/github.com/a-castellano/music-manager-config-reader
  script:
    - echo $GOPATH
    - pwd
    - make test

lint_code:
  stage: unit_tests
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-config-reader
    - cd $GOPATH/src/github.com/a-castellano/music-manager-config-reader
  script:
    - make lint

coverage:
  stage: coverage
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-config-reader
    - cd $GOPATH/src/github.com/a-castellano/music-manager-config-reader
  script:
    - make coverage
  coverage: /total:\s+.+\s(\d+\.\d+?)%$/
  artifacts:
    name: "coverage-$CI_PIPELINE_ID"
    paths:
      - cover
    expire_in: 1 hour

code_coverage_report:
  stage: report
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-config-reader
    - cd $GOPATH/src/github.com/a-castellano/music-manager-config-reader
  script:
    - make coverhtml
  only:
  - master
  dependencies:
  - coverage
  artifacts:
    name: "coverage-$CI_PIPELINE_ID"
    paths:
      - coverage.html
      - cover
    expire_in: 1 hour

scan:
  stage: scan
  image: daedalusproject/base_sonar_scanner
  script:
  - sonar-scanner -Dsonar.projectKey=config-reader -Dsonar.sources=. -Dsonar.host.url=https://sonarqube.windmaker.net -Dsonar.login=${SONAR_LOGIN} -Dsonar.exclusions="*/*_test.go" -Dsonar.go.coverage.reportPaths="cover/coverage.report"
  dependencies:
  - coverage

pages:
  stage: deploy
  image: registry.windmaker.net:5005/a-castellano/limani/base:202104052102
  script:
  - mkdir -p public
  - cp coverage.html public/
  artifacts:
    paths:
    - public
  only:
  - master
  dependencies:
  - code_coverage_report
