[incoming]
name = "incoming"
durable = true
delete_when_unused = false
exclusive = false
no_wait = false
auto_ack = false

[outgoing]
name = "outgoing"
durable = true
delete_when_unused = false
exclusivee = false
no_wait = false
auto_ack = false

